sudo: false
language: scala
jdk: oraclejdk8
scala:
  - 2.12.8
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
before_install:
  - |
    if [[ $TRAVIS_PULL_REQUEST == false ]]; then
      openssl aes-256-cbc -K $encrypted_0ae33bd734a9_key -iv $encrypted_0ae33bd734a9_iv -in travis/secrets.tar.enc -out travis/local.secrets.tar -d;
      tar xv -C travis -f travis/local.secrets.tar;
    fi
after_success:
  - |-
    if [[ $TRAVIS_PULL_REQUEST == false ]]; then
      sbt ++$TRAVIS_SCALA_VERSION publishSigned;
    fi